# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Zero Purpose
tagline:          
description:      ""
url:              http://lguoyu.github.io
baseurl:          /
excerpt_separator: <!--more-->

author:
  name:           'Li Guoyu'
  url:            http://lguoyu.github.io

paginate:         20

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/lguoyu/lguoyu.github.io
