# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Zero Purpose
tagline:          
description:      ""
url:              https://github.com/karloespiritu/blackdoc
baseurl:          /

author:
  name:           'Li Guoyu'
  url:            https://twitter.com/karloespiritu

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/karloespiritu/blackdoc
